# Generated by Django 4.2.4 on 2023-09-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('CollegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Subjectcode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subjectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('CollegeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoapp.college')),
            ],
        ),
    ]
